### PR TITLE
[FEAT] home page

### PR DESCRIPTION
**Pull request by ch3ber**
I create a home page and footer component

### CODE REVIEW

**Comment by ch3ber** [comment]
Please give feedback and before close the PR add the label `hacktoberfest-accepted`

**Comment by muhammad-ahmed02** [comment]
Thank you for the PR, I saw the page but I see it is not responsive can you improve further responsiveness? also, can you make the footer links text in 1 line?

**Comment by muhammad-ahmed02** [comment]
Try to use mui components as they are better for reusable components also they are responsive

**Comment by ch3ber** [comment]
No problem,  I can work on it until [20:30h MX ](https://time.is/es/Monterrey)

**Comment by ch3ber** [comment]
Do you have a link to add on the page?

**Comment by muhammad-ahmed02** [comment]
> Do you have a link to add on the page?

no, the links you added are good as well

**Review by muhammad-ahmed02 — CHANGES_REQUESTED** [review]
Thank you for the PR, please take a pull from the repo and delete the package-lock.json file from the PR and make the page responsive. It would be better if you use Material UI for the components as they are more responsive and require less effort fro development.

**Pull request closed without merging**
