### PR TITLE
[FEAT] home page

### PR DESCRIPTION
**Pull request by ch3ber**
I create a home page, footer component and fix bug of routes

### CODE REVIEW

**Comment by ch3ber** [comment]
Netlify is not running the `npm install` command, please clear the netlify cache and redeploy the app

**Comment by muhammad-ahmed02** [comment]
The site is live

**Comment by muhammad-ahmed02** [comment]
lint is not working and the app can't be compiled can you make it work? else you can remove the lint

**Comment by ch3ber** [comment]
Ok I'm working on it

**Comment by ch3ber** [comment]
@muhammad-ahmed02 I fix all bugs

**Comment by ch3ber** [comment]
The PR is ready to merge

**Review by muhammad-ahmed02 — APPROVED** [review]
Thank you for your contribution, code looks good now. Much appreciated!

**Pull request merged**
